CREATE
NONCLUSTERED INDEX IX_CONTACT_ENTITY_ACCOUNT_ID_COMPANY_ID ON contact (account_id, company_id)
GO

CREATE
NONCLUSTERED INDEX IX_CONTACT_ENTITY_CREATED_BY_COMPANY_ID ON contact (created_by, company_id)
GO

CREATE
NONCLUSTERED INDEX IX_CONTACT_ENTITY_MODIFIED_BY_COMPANY_ID ON contact (modified_by, company_id)
GO

CREATE
NONCLUSTERED INDEX IX_DATA_ROOM_ACCOUNT_ID_COMPANY_ID ON data_room (account_id, company_id)
GO

CREATE
NONCLUSTERED INDEX IX_DATA_ROOM_CONTENT_CREATED_BY ON data_room_content (created_by)
GO

CREATE
NONCLUSTERED INDEX IX_DATA_ROOM_CONTENT_MODIFIED_BY_BY ON data_room_content (modified_by)
GO

CREATE
NONCLUSTERED INDEX IX_DATA_ROOM_CREATED_BY_COMPANY_ID ON data_room (created_by, company_id)
GO

CREATE
NONCLUSTERED INDEX IX_DATA_ROOM_MODIFIED_BY_COMPANY_ID ON data_room (modified_by, company_id)
GO

CREATE
NONCLUSTERED INDEX IX_DATA_ROOM_USER_CREATED_BY ON data_room_user (created_by)
GO

CREATE
NONCLUSTERED INDEX IX_DIRECTORY_ENTITY_CREATED_BY_COMPANY_ID ON directory_entity (created_by, company_id)
GO

CREATE
NONCLUSTERED INDEX IX_DIRECTORY_ENTITY_MODIFIED_BY_COMPANY_ID ON directory_entity (modified_by, company_id)
GO

CREATE
NONCLUSTERED INDEX IX_DOCUMENT_CREATED_BY ON document (created_by)
GO

CREATE
NONCLUSTERED INDEX IX_FILE_CONTENT_CREATED_BY ON file_content (created_by)
GO

CREATE
NONCLUSTERED INDEX IX_FILE_CONTENT_MODIFIED_BY ON file_content (modified_by)
GO

CREATE
NONCLUSTERED INDEX IX_FILE_ENTITY_CREATED_BY_COMPANY_ID ON file_entity (created_by, company_id)
GO

CREATE
NONCLUSTERED INDEX IX_FILE_ENTITY_MODIFIED_BY_COMPANY_ID ON file_entity (modified_by, company_id)
GO

CREATE
NONCLUSTERED INDEX IX_LINK_CREATED_BY_COMPANY_ID ON link (created_by, company_id)
GO

CREATE
NONCLUSTERED INDEX IX_WATERMARK_CREATED_BY_COMPANY_ID ON watermark (created_by, company_id)
GO

CREATE
NONCLUSTERED INDEX IX_WATERMARK_MODIFIED_BY_COMPANY_ID ON watermark (modified_by, company_id)
GO
