CREATE NONCLUSTERED INDEX [IX_DATA_ROOM_NAME_COMPANY_ID] ON[dbo].[data_room]
    (
     [name] ASC,
     [company_id]
        )
    INCLUDE ([created_date]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO